---
- name: sync files from host to nodes
  hosts: all
  become: yes

  handlers:
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded

  tasks:
  - name: create nginx directories
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
    with_items:
      - /var/www/galenguyer.com
      - /var/www/cdn.galenguyer.com
      - /var/www/packages.galenguyer.com

  - name: sync cdn files
    ansible.posix.synchronize:
      src: /var/www/cdn.galenguyer.com/
      dest: /var/www/cdn.galenguyer.com/
      delete: yes
      recursive: yes

  - name: sync packages files
    ansible.posix.synchronize:
      src: /var/www/packages.galenguyer.com/
      dest: /var/www/packages.galenguyer.com/
      delete: yes
      recursive: yes

  - name: sync homepage files
    ansible.posix.synchronize:
      src: /var/www/galenguyer.com/
      dest: /var/www/galenguyer.com/
      delete: yes
      recursive: yes

  - name: sync letsencrypt certs
    ansible.posix.synchronize:
      src: /etc/letsencrypt/
      dest: /etc/letsencrypt/
      delete: yes
      recursive: yes
    notify: reload nginx

  - name: sync nginx configs
    ansible.posix.synchronize:
      src: ../nginx/
      dest: /etc/nginx/
      delete: yes
      recursive: yes
    notify: reload nginx
