---
- name: sync files from host to nodes
  hosts: all
  become: yes

  tasks:

  - name: create web directories
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
    with_items:
      - /var/www/cdn.galenguer.com
      - /var/www/galenguer.com

  - name: sync cdn files
    ansible.posix.synchronize:
      src: /var/www/cdn.galenguyer.com/
      dest: "/var/www/cdn.galenguyer.com/"
      delete: yes
      recursive: yes

  - name: sync homepage files
    ansible.posix.synchronize:
      src: /var/www/galenguyer.com/
      dest: "/var/www/galenguyer.com/"
      delete: yes
      recursive: yes
