---
- name: sync files from host to nodes
  hosts: all
  become: yes

  handlers:
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded

  tasks:
  - name: create nginx directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /var/www/galenguyer.com
      - /var/www/cdn.galenguyer.com
      - /var/www/packages.galenguyer.com

  - name: sync static files
    ansible.posix.synchronize:
      src: "{{ item }}"
      dest: "{{ item }}"
      delete: yes
      recursive: yes
    with_items:
      - /var/www/galenguyer.com/
      - /var/www/cdn.galenguyer.com/
      - /var/www/packages.galenguyer.com/
      - /var/www/ip.nyaa.gay/

  - name: sync letsencrypt certs
    ansible.posix.synchronize:
      src: /etc/letsencrypt/
      dest: /etc/letsencrypt/
      delete: yes
      recursive: yes
    notify: reload nginx

  - name: sync nginx configs
    ansible.posix.synchronize:
      src: ../nginx/
      dest: /etc/nginx/
      delete: yes
      recursive: yes
    notify: reload nginx
