---
- name: sync files from host to nodes
  hosts: all
  become: yes

  handlers:
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded

  tasks:
  - name: sync cdn files
    ansible.posix.synchronize:
      src: /var/www/cdn.galenguyer.com/
      dest: /var/www/cdn.galenguyer.com/
      delete: yes
      recursive: yes

  - name: sync homepage files
    ansible.posix.synchronize:
      src: /var/www/galenguyer.com/
      dest: /var/www/galenguyer.com/
      delete: yes
      recursive: yes

  - name: sync letsencrypt certs
    ansible.posix.synchronize:
      src: /etc/letsencrypt/
      dest: /etc/letsencrypt/
      delete: yes
      recursive: yes
    notify: reload nginx

  - name: sync nginx configs
    ansible.posix.synchronize:
      src: ../nginx/
      dest: /etc/nginx/
      delete: yes
      recursive: yes
    notify: reload nginx
