---
- name: update and install packages
  hosts: all
  become: yes

  tasks:
  - name: update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install required packages
    apt:
      pkg:
        - nginx
        - rsync
        - php-fpm
        - git

  - name: clean apt cache
    apt:
      autoclean: yes

  - name: remove unused packages
    apt:
      autoremove: yes
